= ui.kak

Toggle UI options in http://kakoune.org[Kakoune].

== Installation

Add link:rc/ui.kak[`ui.kak`] to your autoload or source it manually.

== What's included

`ui.kak` provides a `ui` mode for toggling various user interface options (highlighters) and related hooks. All of the following commands are grouped in the in the `ui` user mode with dedicated key mappings.

*ui-line-numbers-toggle*::
    Display line numbers.

*ui-whitespaces-toggle*::
    Display whitespaces.

*ui-trailing-spaces-toggle*::
    Display trailing spaces.

*ui-wrap-toggle*::
    Wrap lines to window width.

*ui-matching-toggle*::
    Display matching char.

*ui-git-diff-toggle*::
    Display https://github.com/mawww/kakoune/blob/master/rc/tools/git.kak[git diff].
    When enabled, this command also adds hooks for automatically updating git diff on `BufWritePost` and `BufReload`. Disabling removes the hooks.

*ui-search-toggle*::
    Dynamically display matches results using `Search` face.
    When enabled, this command also adds hooks to highlight search matches on `/`,`?`,`*`,`n` and `N` keys.
    Pressing `<esc>` removes the highlights.

*ui-todos-toggle*::
    Display `TODO`, `FIXME`, `XXX`, `NOTE` in buffer using `TodoComment` face.

*ui-cursorline-toggle*::
    Display current cursor line using `CursorLine` face.

*ui-cursorcolumn-toggle*::
    Display current cursor column using `CursorColumn` face.

== Suggested configuration

[source,kak]
----
dasdfasdf
----
